from __future__ import annotations

import hashlib

import streamlit as st


st.set_page_config(
    page_title="Media Bias Analysis | Prototype",
    page_icon="📰",
    layout="wide",
)

st.markdown(
    """
    <style>
      .block-container {max-width: 1180px; padding-top: 2rem; padding-bottom: 3rem;}
      .hero {padding: 1.4rem 1.6rem; border-radius: 18px;
        background: linear-gradient(120deg,#102a43 0%,#155e75 100%); color: white;}
      .hero h1 {color: white; margin: 0 0 .35rem 0; font-size: 2.1rem;}
      .hero p {color: #e2f2f7; margin: 0; font-size: 1rem;}
      .demo-note {padding: .8rem 1rem; border-left: 5px solid #f0a202;
        border-radius: 8px; background: #fff8e8; color: #573d00;}
      .model-card {padding: 1rem; border: 1px solid #d9e2ec; border-radius: 14px;
        background: #fff; min-height: 118px;}
      .model-card h3 {margin: 0 0 .45rem 0; font-size: 1.08rem; color: #102a43;}
      .model-card p {margin: 0; color: #52606d; font-size: .92rem;}
      .verdict {padding: 1rem; border-radius: 12px; background: #f0f4f8;}
    </style>
    <div class="hero">
      <h1>Media Bias Analysis</h1>
      <p>Sentence-level research prototype · compare sentence-only and context-aware approaches</p>
    </div>
    """,
    unsafe_allow_html=True,
)

st.write("")
st.markdown(
    '<div class="demo-note"><b>Demonstration mode:</b> outputs below are seeded examples for the defense prototype. '
    'They are not generated by trained model checkpoints and must not be presented as research predictions.</div>',
    unsafe_allow_html=True,
)

SAMPLES = {
    "Choose an example…": {
        "sentence": "",
        "article": "",
        "key": "empty",
    },
    "Example 1 · Loaded language": {
        "sentence": "The mayor's reckless decision devastated the community, critics said.",
        "article": "Residents gathered outside city hall on Tuesday. The mayor's reckless decision devastated the community, critics said. The mayor's office said the policy was intended to reduce costs.",
        "key": "loaded",
    },
    "Example 2 · More neutral wording": {
        "sentence": "The city council approved the revised transportation budget on Tuesday.",
        "article": "The proposal was discussed during two public meetings. The city council approved the revised transportation budget on Tuesday. The budget allocates additional funds for bus maintenance.",
        "key": "neutral",
    },
}

with st.container(border=True):
    st.subheader("1. Add text to analyze")
    chosen = st.selectbox("Start with a seeded example or enter your own text", list(SAMPLES))
    sample = SAMPLES[chosen]
    sentence = st.text_area(
        "Target sentence",
        value=sample["sentence"],
        height=105,
        placeholder="Paste one sentence from a news article…",
        key=f"sentence_{chosen}",
    )
    article = st.text_area(
        "Article text (optional; gives the context model nearby sentences)",
        value=sample["article"],
        height=150,
        placeholder="Paste the article text here…",
        key=f"article_{chosen}",
    )

st.subheader("2. Choose a model view")
model_cols = st.columns(3)
model_info = [
    ("baseline", "Baseline replication", "Sentence only · notebook 02"),
    ("matched", "Controlled baseline", "Sentence only · matched pilot"),
    ("enhanced", "Enhanced model", "Sentence + nearby article context"),
]
for col, (_, title, description) in zip(model_cols, model_info):
    with col:
        st.markdown(
            f'<div class="model-card"><h3>{title}</h3><p>{description}</p></div>',
            unsafe_allow_html=True,
        )

if "demo_results" not in st.session_state:
    st.session_state.demo_results = {}


def seeded_demo_result(model_key: str, sample_key: str, text: str) -> tuple[str, int]:
    """Stable illustrative values; intentionally not a classifier."""
    presets = {
        "loaded": {"baseline": ("Biased", 78), "matched": ("Biased", 75), "enhanced": ("Biased", 84)},
        "neutral": {"baseline": ("Non-biased", 82), "matched": ("Non-biased", 80), "enhanced": ("Non-biased", 88)},
    }
    if sample_key in presets:
        return presets[sample_key][model_key]
    # Hash-based placeholder makes a custom-text demonstration stable between reruns.
    digest = hashlib.sha256((model_key + text.casefold()).encode("utf-8")).digest()
    score = 55 + digest[0] % 36
    label = "Biased" if digest[1] % 2 else "Non-biased"
    return label, score


buttons = st.columns(3)
button_labels = ["Run baseline example", "Run controlled example", "Run enhanced example"]
for col, (model_key, _, _), label in zip(buttons, model_info, button_labels):
    with col:
        if st.button(label, use_container_width=True, disabled=not sentence.strip(), key=f"run_{model_key}"):
            st.session_state.demo_results[model_key] = seeded_demo_result(model_key, sample["key"], sentence)

if st.session_state.demo_results:
    st.subheader("Example analysis results")
    st.caption("Illustrative seeded output only · scores are placeholders, not model confidence values.")
    result_cols = st.columns(3)
    for col, (model_key, title, description) in zip(result_cols, model_info):
        with col:
            if model_key in st.session_state.demo_results:
                label, score = st.session_state.demo_results[model_key]
                other = 100 - score
                st.markdown(f"**{title}**")
                st.markdown('<div class="verdict">', unsafe_allow_html=True)
                st.metric("Demo label", label)
                st.progress(score / 100, text=f"Illustrative score: {score}%")
                st.caption(f"Other class: {other}% · {description}")
                st.markdown("</div>", unsafe_allow_html=True)
            else:
                st.info("Select this model's button to show its seeded example result.")

with st.expander("How to explain this prototype at the defense"):
    st.markdown(
        "The interface demonstrates the intended user flow: enter a target sentence, optionally provide its article, "
        "and inspect outputs for the baseline, matched sentence-only pilot, and context-fusion approach. The displayed "
        "labels and scores are mock examples used to demonstrate the interface; they do not come from the trained models. "
        "A later implementation can connect each button to its corresponding saved checkpoint."
    )

st.caption("Research scope: sentence-level media-bias label demonstration. This prototype does not assess factual accuracy or source credibility.")
